# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(703, 476)
        MainWindow.setMinimumSize(QtCore.QSize(703, 476))
        MainWindow.setMaximumSize(QtCore.QSize(703, 476))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.tab1 = QtWidgets.QWidget()
        self.tab1.setObjectName("tab1")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.tab1)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.pokemon_density = QtWidgets.QCheckBox(self.tab1)
        self.pokemon_density.setTristate(False)
        self.pokemon_density.setObjectName("pokemon_density")
        self.gridLayout_3.addWidget(self.pokemon_density, 0, 1, 1, 1, QtCore.Qt.AlignLeft)
        self.spinBoxTrapDensity = QtWidgets.QSpinBox(self.tab1)
        self.spinBoxTrapDensity.setMaximum(50)
        self.spinBoxTrapDensity.setProperty("value", 10)
        self.spinBoxTrapDensity.setObjectName("spinBoxTrapDensity")
        self.gridLayout_3.addWidget(self.spinBoxTrapDensity, 2, 3, 1, 1, QtCore.Qt.AlignLeft)
        self.kecleon_percentage = QtWidgets.QCheckBox(self.tab1)
        self.kecleon_percentage.setObjectName("kecleon_percentage")
        self.gridLayout_3.addWidget(self.kecleon_percentage, 18, 0, 1, 1)
        self.trap_spawns = QtWidgets.QCheckBox(self.tab1)
        self.trap_spawns.setChecked(True)
        self.trap_spawns.setObjectName("trap_spawns")
        self.gridLayout_3.addWidget(self.trap_spawns, 2, 0, 1, 1)
        self.spinBoxHiddenStairs = QtWidgets.QSpinBox(self.tab1)
        self.spinBoxHiddenStairs.setMaximum(100)
        self.spinBoxHiddenStairs.setSingleStep(10)
        self.spinBoxHiddenStairs.setProperty("value", 10)
        self.spinBoxHiddenStairs.setObjectName("spinBoxHiddenStairs")
        self.gridLayout_3.addWidget(self.spinBoxHiddenStairs, 21, 1, 1, 1, QtCore.Qt.AlignLeft)
        self.spinBoxPokemonDensity = QtWidgets.QSpinBox(self.tab1)
        self.spinBoxPokemonDensity.setMaximum(50)
        self.spinBoxPokemonDensity.setProperty("value", 10)
        self.spinBoxPokemonDensity.setObjectName("spinBoxPokemonDensity")
        self.gridLayout_3.addWidget(self.spinBoxPokemonDensity, 0, 3, 1, 1, QtCore.Qt.AlignLeft)
        self.hallway_density = QtWidgets.QCheckBox(self.tab1)
        self.hallway_density.setObjectName("hallway_density")
        self.gridLayout_3.addWidget(self.hallway_density, 5, 1, 1, 1, QtCore.Qt.AlignLeft)
        self.weather = QtWidgets.QCheckBox(self.tab1)
        self.weather.setChecked(False)
        self.weather.setObjectName("weather")
        self.gridLayout_3.addWidget(self.weather, 12, 0, 1, 1)
        self.trap_density = QtWidgets.QCheckBox(self.tab1)
        self.trap_density.setObjectName("trap_density")
        self.gridLayout_3.addWidget(self.trap_density, 2, 1, 1, 1, QtCore.Qt.AlignLeft)
        self.hallway_length = QtWidgets.QCheckBox(self.tab1)
        self.hallway_length.setObjectName("hallway_length")
        self.gridLayout_3.addWidget(self.hallway_length, 5, 0, 1, 1)
        self.hidden_stairs = QtWidgets.QCheckBox(self.tab1)
        self.hidden_stairs.setObjectName("hidden_stairs")
        self.gridLayout_3.addWidget(self.hidden_stairs, 21, 0, 1, 1)
        self.music = QtWidgets.QCheckBox(self.tab1)
        self.music.setChecked(True)
        self.music.setObjectName("music")
        self.gridLayout_3.addWidget(self.music, 8, 0, 1, 1)
        self.pokemon_spawns = QtWidgets.QCheckBox(self.tab1)
        self.pokemon_spawns.setChecked(True)
        self.pokemon_spawns.setObjectName("pokemon_spawns")
        self.gridLayout_3.addWidget(self.pokemon_spawns, 0, 0, 1, 1)
        self.darkness = QtWidgets.QCheckBox(self.tab1)
        self.darkness.setChecked(True)
        self.darkness.setObjectName("darkness")
        self.gridLayout_3.addWidget(self.darkness, 10, 0, 1, 1)
        self.water_density = QtWidgets.QCheckBox(self.tab1)
        self.water_density.setObjectName("water_density")
        self.gridLayout_3.addWidget(self.water_density, 6, 1, 1, 1, QtCore.Qt.AlignLeft)
        self.spinBoxItemDensity = QtWidgets.QSpinBox(self.tab1)
        self.spinBoxItemDensity.setMaximum(50)
        self.spinBoxItemDensity.setProperty("value", 10)
        self.spinBoxItemDensity.setObjectName("spinBoxItemDensity")
        self.gridLayout_3.addWidget(self.spinBoxItemDensity, 1, 3, 1, 1, QtCore.Qt.AlignLeft)
        self.floor_structure = QtWidgets.QCheckBox(self.tab1)
        self.floor_structure.setObjectName("floor_structure")
        self.gridLayout_3.addWidget(self.floor_structure, 3, 0, 1, 1)
        self.terrain_appearance = QtWidgets.QCheckBox(self.tab1)
        self.terrain_appearance.setChecked(True)
        self.terrain_appearance.setObjectName("terrain_appearance")
        self.gridLayout_3.addWidget(self.terrain_appearance, 7, 0, 1, 1)
        self.spinBoxWaterDensity = QtWidgets.QSpinBox(self.tab1)
        self.spinBoxWaterDensity.setMaximum(50)
        self.spinBoxWaterDensity.setProperty("value", 10)
        self.spinBoxWaterDensity.setObjectName("spinBoxWaterDensity")
        self.gridLayout_3.addWidget(self.spinBoxWaterDensity, 6, 3, 1, 1, QtCore.Qt.AlignLeft)
        self.water_percentage = QtWidgets.QCheckBox(self.tab1)
        self.water_percentage.setObjectName("water_percentage")
        self.gridLayout_3.addWidget(self.water_percentage, 20, 0, 1, 1)
        self.item_spawns = QtWidgets.QCheckBox(self.tab1)
        self.item_spawns.setChecked(True)
        self.item_spawns.setObjectName("item_spawns")
        self.gridLayout_3.addWidget(self.item_spawns, 1, 0, 1, 1)
        self.water = QtWidgets.QCheckBox(self.tab1)
        self.water.setObjectName("water")
        self.gridLayout_3.addWidget(self.water, 6, 0, 1, 1)
        self.enemy_iq = QtWidgets.QCheckBox(self.tab1)
        self.enemy_iq.setChecked(False)
        self.enemy_iq.setObjectName("enemy_iq")
        self.gridLayout_3.addWidget(self.enemy_iq, 11, 0, 1, 1)
        self.item_density = QtWidgets.QCheckBox(self.tab1)
        self.item_density.setObjectName("item_density")
        self.gridLayout_3.addWidget(self.item_density, 1, 1, 1, 1, QtCore.Qt.AlignLeft)
        self.spinBoxHallwayDensity = QtWidgets.QSpinBox(self.tab1)
        self.spinBoxHallwayDensity.setMaximum(50)
        self.spinBoxHallwayDensity.setProperty("value", 10)
        self.spinBoxHallwayDensity.setObjectName("spinBoxHallwayDensity")
        self.gridLayout_3.addWidget(self.spinBoxHallwayDensity, 5, 3, 1, 1, QtCore.Qt.AlignLeft)
        self.spinBoxRoomDensity = QtWidgets.QSpinBox(self.tab1)
        self.spinBoxRoomDensity.setMaximum(50)
        self.spinBoxRoomDensity.setProperty("value", 10)
        self.spinBoxRoomDensity.setObjectName("spinBoxRoomDensity")
        self.gridLayout_3.addWidget(self.spinBoxRoomDensity, 3, 3, 1, 1, QtCore.Qt.AlignLeft)
        self.monster_house = QtWidgets.QCheckBox(self.tab1)
        self.monster_house.setObjectName("monster_house")
        self.gridLayout_3.addWidget(self.monster_house, 19, 0, 1, 1)
        self.room_density = QtWidgets.QCheckBox(self.tab1)
        self.room_density.setObjectName("room_density")
        self.gridLayout_3.addWidget(self.room_density, 3, 1, 1, 1, QtCore.Qt.AlignLeft)
        self.spinBoxWaterRoom = QtWidgets.QSpinBox(self.tab1)
        self.spinBoxWaterRoom.setMaximum(100)
        self.spinBoxWaterRoom.setSingleStep(10)
        self.spinBoxWaterRoom.setProperty("value", 10)
        self.spinBoxWaterRoom.setObjectName("spinBoxWaterRoom")
        self.gridLayout_3.addWidget(self.spinBoxWaterRoom, 20, 1, 1, 1, QtCore.Qt.AlignLeft)
        self.spinBoxMonsterHouse = QtWidgets.QSpinBox(self.tab1)
        self.spinBoxMonsterHouse.setMaximum(100)
        self.spinBoxMonsterHouse.setSingleStep(10)
        self.spinBoxMonsterHouse.setProperty("value", 10)
        self.spinBoxMonsterHouse.setObjectName("spinBoxMonsterHouse")
        self.gridLayout_3.addWidget(self.spinBoxMonsterHouse, 19, 1, 1, 1, QtCore.Qt.AlignLeft)
        self.spinBoxKecleonShop = QtWidgets.QSpinBox(self.tab1)
        self.spinBoxKecleonShop.setMaximum(100)
        self.spinBoxKecleonShop.setSingleStep(10)
        self.spinBoxKecleonShop.setProperty("value", 10)
        self.spinBoxKecleonShop.setObjectName("spinBoxKecleonShop")
        self.gridLayout_3.addWidget(self.spinBoxKecleonShop, 18, 1, 1, 1, QtCore.Qt.AlignLeft)
        self.setPokemon = QtWidgets.QCheckBox(self.tab1)
        self.setPokemon.setObjectName("setPokemon")
        self.gridLayout_3.addWidget(self.setPokemon, 0, 2, 1, 1, QtCore.Qt.AlignRight)
        self.setItem = QtWidgets.QCheckBox(self.tab1)
        self.setItem.setObjectName("setItem")
        self.gridLayout_3.addWidget(self.setItem, 1, 2, 1, 1, QtCore.Qt.AlignRight)
        self.setTrap = QtWidgets.QCheckBox(self.tab1)
        self.setTrap.setObjectName("setTrap")
        self.gridLayout_3.addWidget(self.setTrap, 2, 2, 1, 1, QtCore.Qt.AlignRight)
        self.setRoom = QtWidgets.QCheckBox(self.tab1)
        self.setRoom.setObjectName("setRoom")
        self.gridLayout_3.addWidget(self.setRoom, 3, 2, 1, 1, QtCore.Qt.AlignRight)
        self.setHallway = QtWidgets.QCheckBox(self.tab1)
        self.setHallway.setObjectName("setHallway")
        self.gridLayout_3.addWidget(self.setHallway, 5, 2, 1, 1, QtCore.Qt.AlignRight)
        self.setWater = QtWidgets.QCheckBox(self.tab1)
        self.setWater.setObjectName("setWater")
        self.gridLayout_3.addWidget(self.setWater, 6, 2, 1, 1, QtCore.Qt.AlignRight)
        self.tabWidget.addTab(self.tab1, "")
        self.tab2 = QtWidgets.QWidget()
        self.tab2.setObjectName("tab2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.tab2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.spinBoxTypes = QtWidgets.QSpinBox(self.tab2)
        self.spinBoxTypes.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.spinBoxTypes.setMaximum(100)
        self.spinBoxTypes.setSingleStep(10)
        self.spinBoxTypes.setProperty("value", 50)
        self.spinBoxTypes.setObjectName("spinBoxTypes")
        self.gridLayout_2.addWidget(self.spinBoxTypes, 0, 2, 1, 1, QtCore.Qt.AlignLeft)
        self.type = QtWidgets.QCheckBox(self.tab2)
        self.type.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.type.setAutoFillBackground(False)
        self.type.setChecked(True)
        self.type.setObjectName("type")
        self.gridLayout_2.addWidget(self.type, 0, 0, 1, 1)
        self.iq_group = QtWidgets.QCheckBox(self.tab2)
        self.iq_group.setChecked(True)
        self.iq_group.setObjectName("iq_group")
        self.gridLayout_2.addWidget(self.iq_group, 3, 0, 1, 1)
        self.spinBoxAbilities = QtWidgets.QSpinBox(self.tab2)
        self.spinBoxAbilities.setMaximum(100)
        self.spinBoxAbilities.setSingleStep(10)
        self.spinBoxAbilities.setProperty("value", 50)
        self.spinBoxAbilities.setObjectName("spinBoxAbilities")
        self.gridLayout_2.addWidget(self.spinBoxAbilities, 1, 2, 1, 1, QtCore.Qt.AlignLeft)
        self.label1 = QtWidgets.QLabel(self.tab2)
        self.label1.setObjectName("label1")
        self.gridLayout_2.addWidget(self.label1, 0, 1, 1, 1, QtCore.Qt.AlignRight)
        self.label2 = QtWidgets.QLabel(self.tab2)
        self.label2.setObjectName("label2")
        self.gridLayout_2.addWidget(self.label2, 1, 1, 1, 1, QtCore.Qt.AlignRight)
        self.abilities = QtWidgets.QCheckBox(self.tab2)
        self.abilities.setChecked(True)
        self.abilities.setObjectName("abilities")
        self.gridLayout_2.addWidget(self.abilities, 1, 0, 1, 1)
        self.moveset = QtWidgets.QCheckBox(self.tab2)
        self.moveset.setChecked(True)
        self.moveset.setObjectName("moveset")
        self.gridLayout_2.addWidget(self.moveset, 2, 0, 1, 1)
        self.mobility = QtWidgets.QCheckBox(self.tab2)
        self.mobility.setChecked(True)
        self.mobility.setObjectName("mobility")
        self.gridLayout_2.addWidget(self.mobility, 4, 0, 1, 1)
        self.tabWidget.addTab(self.tab2, "")
        self.tab3 = QtWidgets.QWidget()
        self.tab3.setObjectName("tab3")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.tab3)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.body_size = QtWidgets.QCheckBox(self.tab3)
        self.body_size.setChecked(True)
        self.body_size.setObjectName("body_size")
        self.gridLayout_4.addWidget(self.body_size, 1, 0, 1, 1)
        self.recruit_rate = QtWidgets.QCheckBox(self.tab3)
        self.recruit_rate.setChecked(True)
        self.recruit_rate.setObjectName("recruit_rate")
        self.gridLayout_4.addWidget(self.recruit_rate, 1, 1, 1, 1, QtCore.Qt.AlignRight)
        self.player_starters = QtWidgets.QCheckBox(self.tab3)
        self.player_starters.setChecked(True)
        self.player_starters.setObjectName("player_starters")
        self.gridLayout_4.addWidget(self.player_starters, 0, 0, 1, 1)
        self.spinBoxRecruit = QtWidgets.QSpinBox(self.tab3)
        self.spinBoxRecruit.setPrefix("")
        self.spinBoxRecruit.setMaximum(100)
        self.spinBoxRecruit.setProperty("value", 10)
        self.spinBoxRecruit.setObjectName("spinBoxRecruit")
        self.gridLayout_4.addWidget(self.spinBoxRecruit, 1, 2, 1, 1, QtCore.Qt.AlignLeft)
        self.partner_starters = QtWidgets.QCheckBox(self.tab3)
        self.partner_starters.setChecked(True)
        self.partner_starters.setObjectName("partner_starters")
        self.gridLayout_4.addWidget(self.partner_starters, 0, 1, 1, 1, QtCore.Qt.AlignRight)
        self.portraits = QtWidgets.QCheckBox(self.tab3)
        self.portraits.setChecked(True)
        self.portraits.setObjectName("portraits")
        self.gridLayout_4.addWidget(self.portraits, 3, 0, 1, 1)
        self.legendary = QtWidgets.QCheckBox(self.tab3)
        self.legendary.setChecked(True)
        self.legendary.setObjectName("legendary")
        self.gridLayout_4.addWidget(self.legendary, 2, 0, 1, 1)
        self.tabWidget.addTab(self.tab3, "")
        self.verticalLayout_2.addWidget(self.tabWidget)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.randomize = QtWidgets.QPushButton(self.centralwidget)
        self.randomize.setEnabled(False)
        self.randomize.setObjectName("randomize")
        self.horizontalLayout.addWidget(self.randomize, 0, QtCore.Qt.AlignHCenter)
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.horizontalLayout.addWidget(self.progressBar)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.verticalLayout_3.addLayout(self.verticalLayout_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 703, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.menuFile.addAction(self.actionOpen)
        self.menuHelp.addAction(self.actionAbout)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "PMD Sky Randomizer"))
        self.pokemon_density.setText(_translate("MainWindow", "Pokemon density     "))
        self.kecleon_percentage.setText(_translate("MainWindow", "Kecleon shop percentage"))
        self.trap_spawns.setText(_translate("MainWindow", "Trap spawns"))
        self.spinBoxHiddenStairs.setSuffix(_translate("MainWindow", "%"))
        self.hallway_density.setText(_translate("MainWindow", "Hallway density       "))
        self.weather.setText(_translate("MainWindow", "Weather"))
        self.trap_density.setText(_translate("MainWindow", "Trap density           "))
        self.hallway_length.setText(_translate("MainWindow", "Hallway length"))
        self.hidden_stairs.setText(_translate("MainWindow", "Hidden stairs percentage"))
        self.music.setText(_translate("MainWindow", "Music"))
        self.pokemon_spawns.setText(_translate("MainWindow", "Pokemon spawns"))
        self.darkness.setText(_translate("MainWindow", "Darkness"))
        self.water_density.setText(_translate("MainWindow", "Water/Lava density"))
        self.floor_structure.setText(_translate("MainWindow", "Floor structure"))
        self.terrain_appearance.setText(_translate("MainWindow", "Terrain appearance"))
        self.water_percentage.setText(_translate("MainWindow", "Water/Lava room percentage"))
        self.item_spawns.setText(_translate("MainWindow", "Item spawns"))
        self.water.setText(_translate("MainWindow", "Water/Lava"))
        self.enemy_iq.setText(_translate("MainWindow", "Enemy IQ"))
        self.item_density.setText(_translate("MainWindow", "Item density           "))
        self.monster_house.setText(_translate("MainWindow", "Monster house percentage"))
        self.room_density.setText(_translate("MainWindow", "Room density          "))
        self.spinBoxWaterRoom.setSuffix(_translate("MainWindow", "%"))
        self.spinBoxMonsterHouse.setSuffix(_translate("MainWindow", "%"))
        self.spinBoxKecleonShop.setSuffix(_translate("MainWindow", "%"))
        self.setPokemon.setText(_translate("MainWindow", "Set density:"))
        self.setItem.setText(_translate("MainWindow", "Set density:"))
        self.setTrap.setText(_translate("MainWindow", "Set density:"))
        self.setRoom.setText(_translate("MainWindow", "Set density:"))
        self.setHallway.setText(_translate("MainWindow", "Set density:"))
        self.setWater.setText(_translate("MainWindow", "Set density:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab1), _translate("MainWindow", "Dungeon data"))
        self.spinBoxTypes.setSuffix(_translate("MainWindow", "%"))
        self.type.setText(_translate("MainWindow", "Type"))
        self.iq_group.setText(_translate("MainWindow", "IQ Group"))
        self.spinBoxAbilities.setSuffix(_translate("MainWindow", "%"))
        self.label1.setText(_translate("MainWindow", "Second type chance:"))
        self.label2.setText(_translate("MainWindow", "Second ability chance:"))
        self.abilities.setText(_translate("MainWindow", "Abilities"))
        self.moveset.setText(_translate("MainWindow", "Moveset"))
        self.mobility.setText(_translate("MainWindow", "Terrain mobility"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab2), _translate("MainWindow", "Pokemon data"))
        self.body_size.setText(_translate("MainWindow", "All Pokemon: body size 1*"))
        self.recruit_rate.setText(_translate("MainWindow", "All Pokemon: recruit rate"))
        self.player_starters.setText(_translate("MainWindow", "Randomize players"))
        self.spinBoxRecruit.setSuffix(_translate("MainWindow", "%"))
        self.partner_starters.setText(_translate("MainWindow", "Randomize partners       "))
        self.portraits.setText(_translate("MainWindow", "Fix portraits"))
        self.legendary.setText(_translate("MainWindow", "Legendary Pokemon can spawn!"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab3), _translate("MainWindow", "Other data"))
        self.randomize.setText(_translate("MainWindow", "Randomize"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.actionOpen.setText(_translate("MainWindow", "Open"))
        self.actionAbout.setText(_translate("MainWindow", "About"))
